# Generated by Django 2.2.5 on 2020-09-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=120)),
                ('iddocumento', models.IntegerField(unique=True)),
                ('correo', models.EmailField(max_length=200)),
                ('documento', models.CharField(max_length=10)),
                ('residencia', models.CharField(max_length=200)),
                ('nacimiento', models.CharField(max_length=20)),
                ('telefono', models.IntegerField()),
                ('usuario', models.CharField(max_length=200)),
                ('contraseña', models.CharField(max_length=100)),
            ],
        ),
    ]
